// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[...path].ts";
import * as $1 from "./routes/index.ts";
import * as $2 from "./routes/upload.tsx";
import * as $$0 from "./islands/FileUpload.tsx";

const manifest = {
  routes: {
    "./routes/[...path].ts": $0,
    "./routes/index.ts": $1,
    "./routes/upload.tsx": $2,
  },
  islands: {
    "./islands/FileUpload.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
